### ISSUE TITLE
Booleans metrics converted to Int

### ISSUE THREAD

**Issue by furrowb** [kjstouffer/python-vrops-api-tool#19]
Boolean metrics are converted to Int, making it difficult to discern what the value is.

**Comment by kjstouffer** [comment]
AFAIK vrops only supports `String` and `Double` types for metric values.  Could you give some examples of the metrics that this happens with?

**Comment by furrowb** [comment]
On Hadoop MP, we have a metric (not property) that is a string of a boolean value.  When it shows up in the python tool, it displays false as `4`.

**Comment by kjstouffer** [comment]
The suite-api has two fields for metrics, `data` and `values`. it uses `data` for numeric metrics, and `value` for strings, however, the strings also have the `data` field. for example:
```
					{
						"timestamps": [
							1481520216759
						],
						"statKey": {
							"key": "port_status|status_text"
						},
						"data": [
							24
						],
						"values": [
							"Up"
						]
					},
```
